# Basic set up for three package managers

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily" 
